### ISSUE TITLE
VIM Configuration

### ISSUE THREAD

**Issue by tsmanner** [Vipyr/vimcryption#20]
Create the necessary infrastructure to install and configure VIM to take advantage of vimcryption on all disk access for vimcrypted files.

- [ ] Cipher Type 
- [ ] Keystore Path?
- [ ] Vim API to Add Python Engine Type Dynamically
   - in vimrc:   `:py import new_engine`
   -                  `:Vimcrypt(new_engine, new_engine_type)` 
- [ ] Vimcryption Settings API Bindings
- [ ] g:vimcryption_default_enabled? always encrypt new files? true/false
     - If we save a new file thats a copy of an existing file, (think save-as)
